name: CI
on: push


jobs:
  install:
    name: Install as rez package (py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          index: 0
        - os: macos-latest
          index: 1
        - os: windows-latest
          index: 2

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - uses: j0yu/setup-rez@v1
    - run: rez pip -i requests

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2

    - run: rez build --install --variants ${{ matrix.index }}

    - run: rez env neovim -- which neovim
