name: CI
on: push


jobs:
  install:
    name: Install as rez package (${{ matrix.os }} py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [2.7, 3.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          index: 0
          which: which nvim
        - os: macos-latest
          index: 1
          which: which nvim
        - os: windows-latest
          index: 3  # for 64-bit Windows
          which: where.exe nvim-qt.exe

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - uses: j0yu/setup-rez@v1
      with:
        ref: 2.58.0

    - run: rez pip -i requests

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2

    - run: rez build --install --variants ${{ matrix.index }}

    - run: rez env neovim -- ${{ matrix.which }}
